language: android
android:
  components:
      # The BuildTools version used by your project
      - build-tools-23.0.1
      # The SDK version used to compile your project
      - android-23
      # Additional components
      - extra-android-m2repository

branches:
  only:
    - master

notifications:
  email: false
  
before_cache:
  - rm -f ./RadioControl/gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - ./RadioControl/gradle/caches/
    - ./RadioControl/gradle/wrapper/
    
before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./RadioControl/gradlew -v
  - uname -a

# Let's try to build...
#install: ./gradlew clean build
script: ./RadioControl/gradlew check
