language: android
sudo: false

android:
  components:
      # The BuildTools version used by your project
      - build-tools-23.0.1
      # The SDK version used to compile your project
      - android-23
      # Additional components
      - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
   before_script: cd RadioControl
    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

script: gradle build connectedCheck
